granule:
  resource: {{granule}}
variable: {{variable}}
slicer:
  name: sliceFileByStepSize
  dimension_step_sizes:
    time: 1
    lat: 30
    lon: 30
processors:
  - name: emptyTileFilter
  - name: kelvinToCelsius
  - name: tileSummary
    dataset_name: {{dataset_id}}
  - name: generateTileId

